config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'android/index'
    get 'android/show'
    get 'android/used_coupons'
    get 'android/invitees'
    get 'android/friends'
  end

  devise_for :admins, controllers: { sessions: 'sessions', registrations: 'registrations'}
  namespace :api do
    scope '/v1' do
      resource :sessions, only: [:create] do
        post :request_phone_verification_token
      end

      resource :third_party_accounts, only: :create

      resource :registrations, only: [:create]

      resources :coupons, only: [:index, :show] do
        resources :comments, only: [:index, :create]
        collection do
          get :hot_and_nearby
          get :most_nearby
          get :best_price
          get :best_service
        end

        resources :users, only: [] do
          member do
            get :invitees
          end
        end
      end

      resources :follows, only: [:create] do
        collection do
          delete :destroy
        end
      end

      resources :users, only: [:show, :update] do
        member do
          get :available_coupons
          get :used_coupons
          get :friends
          post :email_registration
          post :email_verification
          post :resend_email_verification
        end
      end

      resources :user_coupons , only: [:create, :update, :show] do
        member do
          get :get_user_coupon
        end
      end
      

      resources :coupon_invitations, only: [:create, :update]

      resource :interactivity_statuses, only: [:index] do
        post :index
      end

      resources :venues, only: [:index, :show] do
        collection do
          get :popular_restaurants
        end
      end

      resources :restaurants, only: [:index, :show] do
        resources :comments, only: [:index, :create]
      end

      resources :envs, only: [:index]

      resources :restaurant_categories do
        member do
          get :restaurants
        end
      end
    end
  end

  namespace :cms do
    resources :coupons
    resources :venues do
      get :photos
      get :reviews
    end
    resources :restaurants
    resources :users
    resources :advertising_events
    resources :partners
    resources :restaurant_categories
    resources :admins, controller: :restaurant_owners, path: :restaurant_owners
    resources :menus
  end
  
  namespace :owner do
    resources :facebook_fanpages
    resources :coupons do
      collection do
        get :code_form
        post :redeem_code
      end
    end
    resources :restaurants

    resources :third_party_accounts, only: [:index] do
      collection do
        get 'page_list'
        post 'sync_data_from_facebook_account'
      end
    end

    resources :advertising_events
    resources :restaurants do
      collection do
        get :connect_a_restaurant
        post :restaurant_reviews
      end
    end
    resources :menus
  end

  get '/auth/facebook'
  get 'auth/:provider/callback' => 'omniauth#omniauth_callback'
  get 'auth/failure' => 'omniauth#omniauth_fallback'
  
  # resources :advertising_events, only: [:show] do
  #   collection do
  #     post '/register_phone' => 'advertising_events#register_phone'
  #     post '/verify_phone' => 'advertising_events#verify_phone'
  #     post '/resend_phone_token' => 'advertising_events#resend_phone_token'
  #     get '/reward' => 'advertising_events#reward'
  #     get '/phone_registration_page' => 'advertising_events#phone_registration_page'
  #     get '/thank_you' => 'advertising_events#thank_you'
  #   end
  # end
  
  namespace :facebook do
    get '/voucher', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    get '/voucher/index', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    post '/voucher/registration', to: 'vouchers#registration'
    post '/voucher/sendsms', to: 'vouchers#send_sms'
    get '/startpage', to: 'vouchers#startpage'
    get '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    post '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    get '/menu', to: 'menu_tabs#index'
    post '/menu', to: 'menu_tabs#index'
  end

  root 'static_pages#index'
  get 'service-intro' => 'static_pages#service_intro'
  get 'app-intro' => 'static_pages#app_intro'
  get 'index' => 'static_pages#index'
  get 'voucher' => 'static_pages#voucher'
end

app/controllers/api/coupons_controller.rb
module Api
  class CouponsController < ActionController::Base
    before_filter :require_location, only: [:hot_and_nearby, :most_nearby]
    
    def index
      render json: ArrayPresenter.new(Coupon.includes(restaurant: [:restaurant_category]).available.page(params[:page]), CouponPresenter)
    end

    def show
      coupon = Coupon.find_by(id: params[:id])
      if coupon.present?
        impressionist(coupon, message: Coupon::VIEW)
        render json: CouponPresenter.new(coupon)
      else
        render_errors(I18n.t("base.api.not_found"), :not_found)
      end
    end

    def most_nearby
      most_nearby_coupons = Coupon.available.most_nearby(params[:latitude], params[:longitude]).page(params[:page]).sort_by(&:distance)
      render json: ArrayPresenter.new(most_nearby_coupons, CouponPresenter)
    end

    def best_price
      best_price_coupons = Coupon.available.most_nearby(params[:latitude], params[:longitude]).best_price.page(params[:page]).sort_by(&:distance)
      render json: ArrayPresenter.new(best_price_coupons, CouponPresenter)
    end

    def best_service
      best_service_coupons = Coupon.available.most_nearby(params[:latitude], params[:longitude]).best_service.page(params[:page]).sort_by(&:distance)
      render json: ArrayPresenter.new(best_service_coupons, CouponPresenter)
    end

    def hot_and_nearby
      hot_nearby_coupons = Coupon.available.hot_and_nearby(params[:latitude], params[:longitude])
      render json: ArrayPresenter.new(hot_nearby_coupons, CouponPresenter)
    end    
   
  end
end

app/controllers/cms/advertising_events_controller.rb
module Cms
  class AdvertisingEventsController < BaseController
    def index
      @advertising_events = AdvertisingEvent.order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('cms.advertising_events.title')
      @advertising_event = AdvertisingEvent.new
    end

    def create
      if advertising_event = AdvertisingEvent.create(advertising_event_params)
        redirect_to cms_advertising_event_path(advertising_event)
      end
    end

    def show
      @advertising_event = AdvertisingEvent.friendly.find(params[:id])
      @users = @advertising_event.users
    end

    def destroy
      if advertising_event = AdvertisingEvent.find_by_id(params[:id])
        advertising_event.destroy
        redirect_to cms_advertising_events_path
      end
    end

    def edit
      @advertising_event = AdvertisingEvent.find_by_id(params[:id])
    end

    def update
      if advertising_event = AdvertisingEvent.friendly.find(params[:id])
        advertising_event.update_attributes(advertising_event_params)
        redirect_to cms_advertising_event_path(advertising_event.id)
      end
    end

    private
    def advertising_event_params
      params.require(:advertising_event).permit(
        :description, :url, :name,
        :home_page_background, :win_page_background, :winning_rate,
        :maximum_number_of_winners, :end_at, :begin_at, :enabled,
        :reference_link_1, :reference_link_2, :user_id
      )
    end
  end
end

app/controllers/cms/base_controller.rb
module Cms
  class BaseController < ApplicationController
    before_action :authenticate_super_admin!, :set_header, :set_side_bar

    def authenticate_super_admin!
      unless current_admin.try(:admin?)
        redirect_to root_path, alert: "Acess Denied!"
      end
    end
  end
end

app/controllers/cms/coupons_controller.rb
module Cms
  class CouponsController < BaseController
    def index
      @coupons = Coupon.order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('cms.coupons.title')
      @coupon = Coupon.new
    end

    def create
      if coupon = Coupon.create(coupon_params)
        redirect_to cms_coupon_path(coupon)
      end
    end

    def show
      @coupon = Coupon.find_by_id(params[:id])
    end

    def destroy
      if coupon = Coupon.find_by_id(params[:id])
        coupon.destroy
        redirect_to cms_coupons_path
      end
    end

    def edit
      @coupon = Coupon.find_by_id(params[:id])
    end

    def update
      if coupon = Coupon.find_by_id(params[:id])
        coupon.update_attributes(coupon_params)
        redirect_to cms_coupon_path(coupon)
      end
    end

    private
    def coupon_params
      params.require(:coupon).permit(
        :description, :venue_id, :image, :restaurant_id,
        :end_date, :start_date, :required_minimum_invitees,
        :short_description, :quantity, :priority, :number_of_free_volka,
        :cash_discount, :bill_discount, :food_discount
      )
    end
  end
end

app/controllers/cms/home_controller.rb
module Cms
  class HomeController < BaseController
    def index
    end
  end
end

app/controllers/cms/menus_controller.rb
module Cms
  class MenusController < BaseController
    def edit
      @menu = Menu.find(params[:id])
    end

    def update
      menu = Menu.find(params[:id])
      if menu.update_attributes(menu_params)
        redirect_to edit_cms_restaurant_path(menu.owner)
      end 
    end

    def new
      @restaurant = Restaurant.find_by_id(params[:restaurant_id])
      @menu = Menu.new
    end

    def create
      menu = Menu.new(menu_params)
      if menu.save
        redirect_to edit_cms_restaurant_path(menu.owner)
      end
    end

    private
    def menu_params
      params.require(:menu).permit!
    end
  end
end

app/controllers/cms/partners_controller.rb
module Cms
  class PartnersController < BaseController
    def index
      @partners = Partner.order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('cms.partners.title')
      @partner = Partner.new
    end

    def create
      if partner = Partner.create(partner_params)
        redirect_to cms_partner_path(partner)
      end
    end

    def show
      @partner = Partner.find_by_id(params[:id])
    end

    def edit
      @partner = Partner.find_by_id(params[:id])
    end

    def update
      if partner = Partner.find_by_id(params[:id])
        partner.update_attributes(partner_params)
        redirect_to cms_partner_path(partner)
      end
    end

    def destroy
      if partner = Partner.find_by_id(params[:id])
        partner.destroy
        redirect_to cms_partners_path
      end
    end

    private
    def partner_params
      params.require(:partner).permit(:name, :url, :image, :active, :order)
    end

  end
end

app/controllers/cms/restaurant_categories_controller.rb
module Cms
  class RestaurantCategoriesController < BaseController
    def index
      @restaurant_categories = RestaurantCategory.all
    end

    def new
      @page_title = t('cms.restaurant_categories.title')
      @restaurant_category = RestaurantCategory.new
    end

    def create
      if restaurant_category = RestaurantCategory.create(restaurant_category_params)
        redirect_to cms_restaurant_category_path(restaurant_category)
      end
    end

    def show
      @restaurant_category = RestaurantCategory.find_by_id(params[:id])
    end

    def destroy
      if restaurant_category = RestaurantCategory.find_by_id(params[:id])
        restaurant_category.destroy
        redirect_to cms_restaurant_categories_path
      end
    end

    def edit
      @restaurant_category = RestaurantCategory.find_by_id(params[:id])
    end

    def update
      if restaurant_category = RestaurantCategory.find_by_id(params[:id])
        restaurant_category.update_attributes(restaurant_category_params)
        redirect_to cms_restaurant_category_path(restaurant_category)
      end
    end

    private
    def restaurant_category_params
      params.require(:restaurant_category).permit(
        :name, :alias, :image
      )
    end
  end
end

app/controllers/cms/restaurant_owners_controller.rb
module Cms
  class RestaurantOwnersController < BaseController
    def index
      @owners = Admin.owners.search(params[:query]).order('updated_at DESC').page(params[:page])
    end

    def show
      @owner = Admin.find_by_id(params[:id])
    end

    def new
      @owner = Admin.new
    end

    def update
      owner = Admin.find_by_id(params[:id])
      if owner.update_owner(owner_params)
        if params[:restaurant_id]
          Restaurant.where(owner: owner).update_all(owner_id: nil, owner_type: nil)
          Restaurant.find_by_id(params[:restaurant_id]).update_attributes(owner: owner)
        end
        redirect_to action: :show, id: owner.id
      else
        redirect_to action: :index
      end
    end

    def edit
      @owner = Admin.find_by_id(params[:id])
    end

    def create
      owner = Admin.new(owner_params)
      if owner.save
        if params[:restaurant_id]
          Restaurant.find_by_id(params[:restaurant_id]).update_attributes(owner: owner)
        end
        RestaurantOwnerInvitationJob.perform_later(owner_params[:email], owner_params[:password])
        redirect_to action: :show, id: owner.id
      else
        redirect_to action: :index
      end
    end

    def destroy
      owner = Admin.find_by_id(params[:id])
      owner.destroy
      redirect_to action: :index
    end

    private
    def owner_params
      params.require(:admin).permit(:id, :phone, :email, :password, :name, venue_ids: [])
    end
  end
end

app/controllers/cms/restaurants_controller.rb
module Cms
  class RestaurantsController < BaseController
    def index
      if params[:city]
        @restaurants = Restaurant.where(city_id: params[:city]).order('name').get_index(page: params[:page])
        @city_id = params[:city]
      else
        @restaurants = Restaurant.order('name').page(params[:page])
      end
      @restaurants = @restaurants.index_by_name(params[:query])

      respond_to do |format|
        format.html
        format.json { render json: Restaurant.index_by_name(params[:query]).pluck(:name, :id) }
      end
    end

    def show
      @restaurant = Restaurant.find_by_id(params[:id])
    end

    def edit
      @restaurant = Restaurant.find(params[:id])
    end

    def update
      restaurant = Restaurant.find_by_id(params[:id])
      if restaurant.update_attributes(restaurant_params)
        redirect_to action: :show, id: restaurant.id
      end
    end

    def destroy
      restaurant = Restaurant.find(params[:id]).destroy
    end

    private
    def restaurant_params
      params.require(:restaurant).permit!
    end
  end
end

app/controllers/cms/users_controller.rb
module Cms
  class UsersController < BaseController
    def index
      @users = User.search(params[:query]).order('updated_at DESC').page(params[:page])
    end

    def show
      @user = User.find_by_id(params[:id])
      client = Koala::Facebook::API.new(@user.facebook_token)
      begin
        data = client.get_object('me', fields: [:age_range])
        @user.update_attributes(age_range: data["age_range"])
      rescue
      end
    end

    def destroy
      user = User.find_by_id(params[:id])
      user.destroy
      redirect_to action: :index
    end
  end
end

app/controllers/cms/venues_controller.rb
module Cms
  class VenuesController < BaseController
    def index
      @venues = Venue.index_by_name(params[:query]).order('updated_at DESC').page(params[:page])
    end

    def new
      @venue = Venue.new
    end

    def create
      if venue = Venue.create(venue_params)
        redirect_to cms_venue_path(venue)
      end
    end

    def show
      @venue = Venue.find_by_id(params[:id])
      Api::VenueDetailsService.new(@venue).get_details
    end

    def destroy
      if venue = Venue.find_by_id(params[:id])
        venue.destroy
        redirect_to cms_venues_path
      end
    end

    def edit
      @venue = Venue.find_by_id(params[:id])
    end

    def update
      if venue = Venue.find_by_id(params[:id]) 
        venue.update_attributes(venue_params)
        redirect_to cms_venue_path(venue)
      end
    end

    def photos
      @venue = Venue.find_by_id(params[:venue_id])
      if @venue
        @google_place_images = @venue.google_place_images
        @facebook_photos = @venue.facebook_photos
      end
    end

    def reviews
      @venue = Venue.find_by_id(params[:venue_id])
      if @venue
        @reviews = @venue.reviews
      end
    end
    private
    def venue_params
      params.require(:venue).permit(
        :name, :description, :latitude, :longitude,
        :full_address, :formatted_phone_number, :website,
        images_attributes: [:id, :content, :_destroy]
      )
    end
  end
end

app/views/cms/coupons/_form.html.haml
= form_for [:cms, coupon] do |f|
  .field
    = f.label :description, t('cms.coupons.description')
    = f.text_area :description, class: 'form-control', disabled: preview

  .field
    = f.label :short_description, t('cms.coupons.short_description')
    = f.text_area :short_description, class: 'form-control', disabled: preview

  .field
    = f.label :restaurant, t('cms.coupons.name_attribute')
    %input{ type: 'text', id: 'restaurant-name-search'}
    = link_to 'Search', '#', id: 'restaurant-name-search', class: 'btn btn-primary'
    = f.select :restaurant_id, Restaurant.order('name').page(1).pluck(:name, :id), { }, { class: 'form-control', disabled: preview }

  .field
    = f.label :priority, t('cms.coupons.priority')
    = f.number_field :priority, class: 'form-control', disabled: preview

  = f.label :start_date, t('cms.coupons.start_date')
  .field.input-group
    %span.input-group-addon
      %i.fa.fa-calendar#coupon-start-date-calendar
    = f.text_field :start_date, 'data-provide' => 'datepicker', class: 'form-control', value: coupon.start_date.try(:strftime, "%d-%m-%Y"), disabled: preview

  = f.label :end_date, t('cms.coupons.end_date')
  .field.input-group    
    %span.input-group-addon
      %i.fa.fa-calendar#coupon-end-date-calendar
    = f.text_field :end_date, 'data-provide' => 'datepicker', class: 'form-control', value: coupon.end_date.try(:strftime, "%d-%m-%Y"), disabled: preview

  = f.label :quantity, t('cms.coupons.quantity')
  .field.input-group
    %span.input-group-addon
      %i.fa.fa-square-o#infinity-quantity
    = f.number_field :quantity, class: 'form-control', disabled: preview

  = f.label :number_of_free_volka, t('cms.coupons.number_of_free_volka')
  .field.input-group
    = f.number_field :number_of_free_volka, class: 'form-control', disabled: preview

  .field
    = f.label :image, t('cms.coupons.image')
    = f.file_field :image, class: 'form-control', disabled: preview
    .image-preview{ id: "image-preview-#{f.options[:child_index]}" }
      = image_tag coupon.image.url

  = f.label :discount, t('cms.coupons.discount')
  .field.input-group
    %span.input-group-addon
      %i= t('cms.coupons.discount_cash')
    = f.text_field :cash_discount, class: 'form-control', disabled: preview
  .field.input-group
    %span.input-group-addon
      %i= t('cms.coupons.discount_bill')
    = f.text_field :bill_discount, class: 'form-control', disabled: preview
  .field.input-group
    %span.input-group-addon
      %i= t('cms.coupons.discount_food')
    = f.text_field :food_discount, class: 'form-control', disabled: preview

  .field
    = f.label :required_minimum_invitees, t('cms.coupons.required_minimum_invitees')
    = f.number_field :required_minimum_invitees, class: 'form-control', disabled: preview

  .field
    = f.label :code, t('cms.coupons.code')
    = f.text_field :code, class: 'form-control', disabled: true, placeholder: t('cms.coupons.code_placeholder')

  .field
    - if preview
      - if current_admin
        = link_to t('cms.actions.go_to_edit'), edit_cms_coupon_path(coupon), class: "btn btn-info"
      - elsif current_restaurant_owner
    - else
      = f.submit "Submit", class: "btn btn-info"

app/views/cms/coupons/_list_of_coupons.html.haml
.row.index-table-row
  .col-md-1
    = t('cms.coupons.id')
  .col-md-3
    = t('cms.coupons.name_attribute')
  .col-md-5
    = t('cms.coupons.description')
  .col-md-3
    = t('cms.actions.label')
- coupons.each_with_index do |coupon, index|
  .row{ class: "index-table-row #{ index%2 == 1 ? 'with-background' : '' }"}
    .col-md-1
      = coupon.id
    .col-md-3
      = coupon.restaurant.try(:name)    
    .col-md-5
      = truncate(coupon.description, length: 40)
    .col-md-3
      - if current_admin.admin?
        = link_to t('cms.actions.show'), cms_coupon_path(coupon), class: 'btn btn-success'
        - if show_action
          = link_to t('cms.actions.edit'), edit_cms_coupon_path(coupon), class: 'btn btn-info'
          = link_to t('cms.actions.delete'), cms_coupon_path(coupon), class: 'btn btn-danger', method: :delete
      - elsif current_admin.owner?
        = link_to t('cms.actions.show'), owner_coupon_path(coupon), class: 'btn btn-success'
        - if show_action
          = link_to t('cms.actions.edit'), edit_owner_coupon_path(coupon), class: 'btn btn-info'

app/views/cms/coupons/_user_coupons_list.html.haml
.row.index-table-row
  .col-md-2
    = t('cms.users.name_attribute')
  .col-md-3
    = t('cms.users.phone_attribute')
  .col-md-3
    = t('cms.users.email_attribute')
  .col-md-3
    = t('cms.coupons.status')
  .col-md-1
    = t('cms.coupons.token')
- user_coupons.each_with_index do |user_coupon, index|
  .row{ class: "index-table-row #{ index%2 == 1 ? 'with-background' : '' }"}
    .col-md-2
      = user_coupon.user.try(:name)
    .col-md-3
      = user_coupon.user.try(:humanized_phone)
    .col-md-3
      = user_coupon.user.try(:email)
    .col-md-3
      = vietnamese_status(user_coupon.status)
    .col-md-1
    = user_coupon.token

app/views/cms/coupons/edit.html.haml
%div
  %span.title= t('cms.coupons.edit')
= render 'form', coupon: @coupon, preview: false

app/views/cms/coupons/index.html.haml
%div
  %span.title= t('cms.coupons.name')
  = link_to t('cms.actions.new'), new_cms_coupon_path, class: 'btn new-record'
= render 'list_of_coupons', coupons: @coupons, show_action: true
= paginate @coupons

app/views/cms/coupons/new.html.haml
%div
  %span.title= t('cms.coupons.new')
= render 'form', coupon: @coupon, preview: false

app/views/cms/coupons/show.html.haml
%div
  %span.title= t('cms.coupons.details')
= render 'form', coupon: @coupon, preview: true
= render 'user_coupons_list', user_coupons: @coupon.user_coupons.includes(:user)