config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'android/index'
    get 'android/show'
    get 'android/used_coupons'
    get 'android/invitees'
    get 'android/friends'
  end

  devise_for :admins, controllers: { sessions: 'sessions', registrations: 'registrations'}
  namespace :api do
    scope '/v1' do
      resource :sessions, only: [:create] do
        post :request_phone_verification_token
      end

      resource :third_party_accounts, only: :create

      resource :registrations, only: [:create]

      resources :coupons, only: [:index, :show] do
        resources :comments, only: [:index, :create]
        collection do
          get :hot_and_nearby
          get :most_nearby
          get :best_price
          get :best_service
        end

        resources :users, only: [] do
          member do
            get :invitees
          end
        end
      end

      resources :follows, only: [:create] do
        collection do
          delete :destroy
        end
      end

      resources :users, only: [:show, :update] do
        member do
          get :available_coupons
          get :used_coupons
          get :friends
          post :email_registration
          post :email_verification
          post :resend_email_verification
        end
      end

      resources :user_coupons , only: [:create, :update, :show] do
        member do
          get :get_user_coupon
        end
      end
      

      resources :coupon_invitations, only: [:create, :update]

      resource :interactivity_statuses, only: [:index] do
        post :index
      end

      resources :venues, only: [:index, :show] do
        collection do
          get :popular_restaurants
        end
      end

      resources :restaurants, only: [:index, :show] do
        resources :comments, only: [:index, :create]
      end

      resources :envs, only: [:index]

      resources :restaurant_categories do
        member do
          get :restaurants
        end
      end
    end
  end

  namespace :cms do
    resources :coupons
    resources :venues do
      get :photos
      get :reviews
    end
    resources :restaurants
    resources :users
    resources :advertising_events
    resources :partners
    resources :restaurant_categories
    resources :admins, controller: :restaurant_owners, path: :restaurant_owners
    resources :menus
  end
  
  namespace :owner do
    resources :facebook_fanpages
    resources :coupons do
      collection do
        get :code_form
        post :redeem_code
      end
    end
    resources :restaurants

    resources :third_party_accounts, only: [:index] do
      collection do
        get 'page_list'
        post 'sync_data_from_facebook_account'
      end
    end

    resources :advertising_events
    resources :restaurants do
      collection do
        get :connect_a_restaurant
        post :restaurant_reviews
      end
    end
    resources :menus
  end

  get '/auth/facebook'
  get 'auth/:provider/callback' => 'omniauth#omniauth_callback'
  get 'auth/failure' => 'omniauth#omniauth_fallback'
  
  # resources :advertising_events, only: [:show] do
  #   collection do
  #     post '/register_phone' => 'advertising_events#register_phone'
  #     post '/verify_phone' => 'advertising_events#verify_phone'
  #     post '/resend_phone_token' => 'advertising_events#resend_phone_token'
  #     get '/reward' => 'advertising_events#reward'
  #     get '/phone_registration_page' => 'advertising_events#phone_registration_page'
  #     get '/thank_you' => 'advertising_events#thank_you'
  #   end
  # end
  
  namespace :facebook do
    get '/voucher', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    get '/voucher/index', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    post '/voucher/registration', to: 'vouchers#registration'
    post '/voucher/sendsms', to: 'vouchers#send_sms'
    get '/startpage', to: 'vouchers#startpage'
    get '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    post '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    get '/menu', to: 'menu_tabs#index'
    post '/menu', to: 'menu_tabs#index'
  end

  root 'static_pages#index'
  get 'service-intro' => 'static_pages#service_intro'
  get 'app-intro' => 'static_pages#app_intro'
  get 'index' => 'static_pages#index'
  get 'voucher' => 'static_pages#voucher'
end

app/controllers/advertising_events_controller.rb
class AdvertisingEventsController < ApplicationController
  layout 'advertising'

  before_filter :facebook_authenticate, only: [:phone_registration_page, :register_phone, :verify_phone, :resend_phone_token, :reward]
  before_filter :required_enabled_advertising_event, only: [:phone_registration_page, :verify_phone]

  def show
    @advertising_event = AdvertisingEvent.friendly.find(params[:id])
  end

  def omniauth_callback
    advertising_event_id = request.env['omniauth.params']['advertising_event_id'] if request.env['omniauth.params']
    omniauth_service = OmniauthService.new(request.env['omniauth.auth'])
    if user = omniauth_service.authenticate_user
      redirect_to action: :phone_registration_page, token: user.facebook_token, email: user.email, advertising_event_id: advertising_event_id
    else
      redirect_to action: :omniauth_fallback
    end
  end

  def phone_registration_page
    @advertising_event = AdvertisingEvent.find_by_id(params[:advertising_event_id])
    if @current_user.joined?(@advertising_event)
      if @current_user.is_winner?(@advertising_event)
        redirect_to action: :reward, email: @current_user.email, token: @current_user.facebook_token, advertising_event_id: @advertising_event.id
      else
        redirect_to action: :thank_you, email: @current_user.email, advertising_event_id: @advertising_event.id
      end
    else
      if @current_user.phone
        PhoneVerificationJob.perform_later(@current_user.id)
      end
    end
  end

  def register_phone
    if existing_user = User.find_by_phone(Api::PhoneParser.normalize(params[:phone]))
      existing_user.facebook_token = @current_user.facebook_token
      existing_user.facebook_token_expiration = @current_user.facebook_token_expiration
      existing_user.facebook_image_url = @current_user.facebook_image_url
      existing_user.email = @current_user.email
      ActiveRecord::Base.transaction do
        @current_user.destroy unless @current_user.id == existing_user.id
        existing_user.save
      end
      PhoneVerificationJob.perform_later(existing_user.id)
      head :ok
    else
      if @current_user.update_attributes(phone: params[:phone], name: params[:name])
        PhoneVerificationJob.perform_later(@current_user.id)
        head :ok
      else
        render json: { messages: @current_user.errors.full_messages }, status: :unprocessable_entity
      end
    end
  end

  def verify_phone
    if @current_user.verification_token == params[:verification_token]
      certificate = UserAdvertisingEvent.new(advertising_event_id: params[:advertising_event_id], user: @current_user)

      if certificate.save
        render json: { win: certificate.won? }
      else
        render json: { messages: I18n.t('advertising_event.general_error') }, status: :unprocessable_entity
      end
    else
      render json: { messages: I18n.t('advertising_event.invalid_verification_code') }, status: :unprocessable_entity
    end
  end

  def resend_phone_token
    PhoneVerificationJob.perform_later(@current_user.id)
    head :ok
  end

  def thank_you
    @user = User.find_by_email(params[:email])
    @advertising_event = AdvertisingEvent.find_by_id(params[:advertising_event_id])
  end

  def reward
    @advertising_event = AdvertisingEvent.find_by_id(params[:advertising_event_id])
  end

  private
  def facebook_authenticate
    unless (@current_user = User.find_by_email(params[:email])) && (@current_user.facebook_token == params[:token])
      redirect_to action: :home
    end
  end

  def required_enabled_advertising_event
    @advertising_event = AdvertisingEvent.find_by_id(params[:advertising_event_id])
    unless @advertising_event.try(:enabled)
      if @advertising_event
        redirect_to action: :show, id: @advertising_event.slug
      else
        redirect_to action: :show, id: "not-found"
      end
    end
  end
end

app/controllers/cms/advertising_events_controller.rb
module Cms
  class AdvertisingEventsController < BaseController
    def index
      @advertising_events = AdvertisingEvent.order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('cms.advertising_events.title')
      @advertising_event = AdvertisingEvent.new
    end

    def create
      if advertising_event = AdvertisingEvent.create(advertising_event_params)
        redirect_to cms_advertising_event_path(advertising_event)
      end
    end

    def show
      @advertising_event = AdvertisingEvent.friendly.find(params[:id])
      @users = @advertising_event.users
    end

    def destroy
      if advertising_event = AdvertisingEvent.find_by_id(params[:id])
        advertising_event.destroy
        redirect_to cms_advertising_events_path
      end
    end

    def edit
      @advertising_event = AdvertisingEvent.find_by_id(params[:id])
    end

    def update
      if advertising_event = AdvertisingEvent.friendly.find(params[:id])
        advertising_event.update_attributes(advertising_event_params)
        redirect_to cms_advertising_event_path(advertising_event.id)
      end
    end

    private
    def advertising_event_params
      params.require(:advertising_event).permit(
        :description, :url, :name,
        :home_page_background, :win_page_background, :winning_rate,
        :maximum_number_of_winners, :end_at, :begin_at, :enabled,
        :reference_link_1, :reference_link_2, :user_id
      )
    end
  end
end

app/controllers/owner/advertising_events_controller.rb
module Owner
  class AdvertisingEventsController < BaseController
    def index
      @advertising_events = AdvertisingEvent.where('user_id = ?', current_admin.id).order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('owner.advertising_events.title')
      @advertising_event = AdvertisingEvent.new
    end

    def create
      advertising_event_params[:user_id] = current_admin.id
      if advertising_event = AdvertisingEvent.create(advertising_event_params)
        redirect_to owner_advertising_event_path(advertising_event)
      end
    end

    def show
      @advertising_event = AdvertisingEvent.friendly.find(params[:id])
      @users = @advertising_event.users
    end

    def destroy
      if advertising_event = AdvertisingEvent.find_by_id(params[:id])
        advertising_event.destroy
        redirect_to owner_advertising_events_path
      end
    end

    def edit
      @advertising_event = AdvertisingEvent.find_by_id(params[:id])
    end

    def update
      if advertising_event = AdvertisingEvent.friendly.find(params[:id])
        advertising_event.update_attributes(advertising_event_params)
        redirect_to owner_advertising_event_path(advertising_event.id)
      end
    end

    private
    def advertising_event_params
      params.require(:advertising_event).permit(
          :description, :url, :name,
          :home_page_background, :win_page_background, :winning_rate,
          :maximum_number_of_winners, :end_at, :begin_at, :enabled,
          :reference_link_1, :reference_link_2, :user_id
      )
    end
  end
end

app/controllers/owner/base_controller.rb
module Owner
  class BaseController < ApplicationController
    before_action :authenticate_restaurant_owner!, :set_header, :set_side_bar

    def current_ability
      @current_ability ||= AdminAbility.new(current_admin)
    end

    def authenticate_restaurant_owner!
      unless current_admin.try(:owner?)
        redirect_to root_path, alert: "Access Denied!"
      end
    end
  end
end

app/controllers/owner/coupons_controller.rb
module Owner
  class CouponsController < BaseController

    def code_form
    end

    def redeem_code
      begin
        coupon = Coupon.find_by(id: params[:coupon_id])
        user_coupon = coupon.user_coupons.find_by(token: params[:code])
        user = user_coupon.user
        if user_coupon.available?
          user_coupon.used!
          render json: { message: "Successfully used coupon for user #{user.representative_name}" }
        else
          render json: { message: "User #{user.representative_name} already used the coupon" }
        end
      rescue
        render json: { message: 'Error happening. Please try it again' }
      end
    end

    private
    def coupon_params
      params.require(:coupon).permit(:quantity)
    end
  end
end

app/controllers/owner/facebook_fanpages_controller.rb
module Owner
  class FacebookFanpagesController < BaseController
    def index
      @facebook_fanpages = current_admin.facebook_fanpages
    end

    def destroy
      facebook_fanpage = FacebookFanpage.find(params[:id]).destroy
      redirect_to action: :index
    end
  end
end

app/controllers/owner/menus_controller.rb
module Owner
  class MenusController < BaseController
    def index
      @menus = current_admin.menus
    end

    def show
      @menu = Menu.find(params[:id])
    end

    def edit
      @menu = Menu.find(params[:id])
    end

    def new
      @menu = Menu.new
    end

    def destroy
      Menu.find(params[:id]).destroy
      redirect_to action: :index
    end

    def update
      menu = Menu.find(params[:id])
      if menu.update_attributes(menu_params)
        redirect_to action: :show, id: menu.id
      end
    end

    def create
      menu = Menu.new(menu_params)
      menu.owner = current_admin
      if menu.save
        redirect_to action: :show, id: menu.id
      end
    end

    private
    def menu_params
      params.require(:menu).permit(:name, :category, :price, :image, menu_components_attributes: [:id, :content, :_destroy])
    end
  end
end

app/controllers/owner/restaurants_controller.rb
module Owner
  class RestaurantsController < BaseController
    def index
      @restaurants = current_admin.restaurants.page(params[:page])
      @searching_restaurants = Restaurant.search_by_name(params[:query]).page(params[:page])
    end

    def restaurant_reviews
      RestaurantWaitListReview.create(facebook_fanpage: current_admin.default_fanpage, restaurant_id: params[:restaurant_id])
    end

    def new
      Facebook::FacebookDataCrawlService.new(current_admin.default_fanpage).update_data(Restaurant.new)
      redirect_to action: :index
    end

    def create
      restaurant = Restaurant.new(restaurant_params)
      restaurant.owner = current_admin.default_fanpage
      if restaurant.save
        redirect_to action: :index
      end
    end

    def edit
      @restaurant = Restaurant.find(params[:id])
    end

    def show
      @restaurant = Restaurant.find(params[:id])
    end

    def update
      restaurant = Restaurant.find(params[:id])
      if restaurant.update_attributes(restaurant_params)
        redirect_to action: :index
      end
    end

    def destroy
      Restaurant.find(params[:id]).destroy
      redirect_to action: :index
    end

    private
    def restaurant_params
      params.require(:restaurant).permit!
    end
  end
end

app/controllers/owner/third_party_accounts_controller.rb
module Owner
  class ThirdPartyAccountsController < BaseController
    before_filter :redirect_to_fanpage_list, only: [:index, :page_list]
    before_filter :set_header_background_color
    skip_before_filter :set_header, :set_side_bar

    def index
      @no_side_bar = true
    end

    def page_list
      @identity = FacebookIdentity.find(params[:identity_id])
      @accounts = @identity.fetch_accounts
    end

    def sync_data_from_facebook_account
      data = JSON.parse(params[:fanpage])
      uid = data["id"]
      name = data["name"]
      access_token = data["access_token"]
      fanpage = FacebookFanpage.new(admin: current_admin, name: name)
      identity = FacebookIdentity.find_or_initialize_by(uid: uid)
      identity.user = fanpage
      identity.access_token = access_token
      if fanpage.save && identity.save
        identity.crawl_facebook_data
        redirect_to owner_facebook_fanpages_path
      else
        redirect_to action: :page_list, identity_id: params[:identity_id]
      end
    end

    private
    def redirect_to_fanpage_list
      unless current_admin.facebook_fanpages.empty?
        redirect_to owner_facebook_fanpages_path
      end
    end
  end
end

app/views/owner/advertising_events/_form.html.haml
= form_for [:owner, advertising_event], html: { multipart: true } do |f|
  .field
    = f.label :name, t('cms.advertising_events.name_attribute')
    = f.text_field :name, class: 'form-control', disabled: preview
  .field
    = f.label :url, t('cms.advertising_events.url')
    = f.text_field :url, class: 'form-control', disabled: preview
  .field
    = f.label :reference_link_1, t('cms.advertising_events.reference_link_1')
    = f.text_field :reference_link_1, class: 'form-control', disabled: preview
  .field
    = f.label :reference_link_2, t('cms.advertising_events.reference_link_2')
    = f.text_field :reference_link_2, class: 'form-control', disabled: preview
  .field
    = f.label :enabled, t('cms.advertising_events.enabled')
    = f.check_box :enabled, class: 'form-control', disabled: preview
  .field
    = f.label :description, t('cms.advertising_events.description')
    = f.text_area :description, class: 'form-control', disabled: preview
  .field
    = f.label :begin_at, t('cms.advertising_events.start_date')
    = f.text_field :begin_at, 'data-provide' => 'datepicker', class: 'form-control', value: advertising_event.begin_at.try(:strftime, "%d-%m-%Y"), disabled: preview
  .field
    = f.label :end_at, t('cms.advertising_events.end_date')
    = f.text_field :end_at, 'data-provide' => 'datepicker', class: 'form-control', value: advertising_event.end_at.try(:strftime, "%d-%m-%Y"), disabled: preview
  .field
    = f.label :winning_rate
    = f.number_field :winning_rate, class: 'form-control', step: 0.01, disabled: preview
  .field
    = f.label :maximum_number_of_winners
    = f.number_field :maximum_number_of_winners, class: 'form-control', disabled: preview
  .field
    = f.label :home_page_background
    = f.file_field :home_page_background, class: 'form-control', disabled: preview
    .image-preview{ id: "image-preview-1" }
      = image_tag advertising_event.home_page_background.url
  .field
    = f.label :win_page_background
    = f.file_field :win_page_background, class: 'form-control', disabled: preview
    .image-preview{ id: "image-preview-2" }
      = image_tag advertising_event.win_page_background.url
  .field
    = f.hidden_field :user_id, value: current_admin.id
  - if preview
    = link_to t('cms.actions.go_to_edit'), edit_owner_advertising_event_path(advertising_event.id), class: "btn btn-info"
  - else
    = f.submit "Submit", class: "btn btn-info"
    

app/views/owner/advertising_events/edit.html.haml
%div
  %span.title= t('cms.advertising_events.edit')
= render 'form', advertising_event: @advertising_event, preview: false

app/views/owner/advertising_events/index.html.haml
%div
  %span.title= t('cms.advertising_events.name')
  = link_to t('cms.actions.new'), new_owner_advertising_event_path, class: 'btn new-record'
.row.index-table-row
  .col-md-1
    = t('cms.advertising_events.id')
  .col-md-4
    = t('cms.advertising_events.name_attribute')
  .col-md-3
    = t('cms.advertising_events.value')
  .col-md-4
    = t('cms.actions.label')
- @advertising_events.each_with_index do |advertising_event, index|
  .row{ class: "index-table-row #{ index%2 == 1 ? 'with-background' : '' }"}
    .col-md-1
      = advertising_event.id
    .col-md-4
      = advertising_event.name
    .col-md-3
      = advertising_event.description
    .col-md-4
      = link_to t('cms.actions.edit'), edit_owner_advertising_event_path(advertising_event.id), class: 'btn btn-primary'
      = link_to t('cms.actions.show'), owner_advertising_event_path(advertising_event.id), class: 'btn btn-info'
      = link_to t('cms.actions.delete'), owner_advertising_event_path(advertising_event.id), class: 'btn btn-danger', method: :delete
= paginate @advertising_events

app/views/owner/advertising_events/new.html.haml
%div
  %span.title= t('owner.menus.new')
= render 'form', menu: @menu, preview: false

app/views/owner/advertising_events/show.html.haml
%div
  %span.title= "Detials (#{@advertising_event.public_link(request.host)})"
= render 'form', advertising_event: @advertising_event, preview: true
.joined-user-list
  %h4
    Nguời dùng tham gia sự kiện
  .row.index-table-row
    .col-md-1
      = t('cms.users.id')
    .col-md-3
      = t('cms.users.name_attribute')
    .col-md-3
      = t('cms.users.phone_attribute')
    .col-md-3
      = t('cms.users.email_attribute')
    .col-md-2
      = t('cms.users.lucky_code')
  - @users.each_with_index do |user, index|
    .row{ class: "index-table-row #{ index%2 == 1 ? 'with-background' : '' }"}
      .col-md-1
        = user.id
      .col-md-3
        = user.name
      .col-md-3
        = user.phone
      .col-md-3
        = user.email
      .col-md-2
        = user.lucky_code(@advertising_event)