config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'android/index'
    get 'android/show'
    get 'android/used_coupons'
    get 'android/invitees'
    get 'android/friends'
  end

  devise_for :admins, controllers: { sessions: 'sessions', registrations: 'registrations'}
  namespace :api do
    scope '/v1' do
      resource :sessions, only: [:create] do
        post :request_phone_verification_token
      end

      resource :third_party_accounts, only: :create

      resource :registrations, only: [:create]

      resources :coupons, only: [:index, :show] do
        resources :comments, only: [:index, :create]
        collection do
          get :hot_and_nearby
          get :most_nearby
          get :best_price
          get :best_service
        end

        resources :users, only: [] do
          member do
            get :invitees
          end
        end
      end

      resources :follows, only: [:create] do
        collection do
          delete :destroy
        end
      end

      resources :users, only: [:show, :update] do
        member do
          get :available_coupons
          get :used_coupons
          get :friends
          post :email_registration
          post :email_verification
          post :resend_email_verification
        end
      end

      resources :user_coupons , only: [:create, :update, :show] do
        member do
          get :get_user_coupon
        end
      end
      

      resources :coupon_invitations, only: [:create, :update]

      resource :interactivity_statuses, only: [:index] do
        post :index
      end

      resources :venues, only: [:index, :show] do
        collection do
          get :popular_restaurants
        end
      end

      resources :restaurants, only: [:index, :show] do
        resources :comments, only: [:index, :create]
      end

      resources :envs, only: [:index]

      resources :restaurant_categories do
        member do
          get :restaurants
        end
      end
    end
  end

  namespace :cms do
    resources :coupons
    resources :venues do
      get :photos
      get :reviews
    end
    resources :restaurants
    resources :users
    resources :advertising_events
    resources :partners
    resources :restaurant_categories
    resources :admins, controller: :restaurant_owners, path: :restaurant_owners
    resources :menus
  end
  
  namespace :owner do
    resources :facebook_fanpages
    resources :coupons do
      collection do
        get :code_form
        post :redeem_code
      end
    end
    resources :restaurants

    resources :third_party_accounts, only: [:index] do
      collection do
        get 'page_list'
        post 'sync_data_from_facebook_account'
      end
    end

    resources :advertising_events
    resources :restaurants do
      collection do
        get :connect_a_restaurant
        post :restaurant_reviews
      end
    end
    resources :menus
  end

  get '/auth/facebook'
  get 'auth/:provider/callback' => 'omniauth#omniauth_callback'
  get 'auth/failure' => 'omniauth#omniauth_fallback'
  
  # resources :advertising_events, only: [:show] do
  #   collection do
  #     post '/register_phone' => 'advertising_events#register_phone'
  #     post '/verify_phone' => 'advertising_events#verify_phone'
  #     post '/resend_phone_token' => 'advertising_events#resend_phone_token'
  #     get '/reward' => 'advertising_events#reward'
  #     get '/phone_registration_page' => 'advertising_events#phone_registration_page'
  #     get '/thank_you' => 'advertising_events#thank_you'
  #   end
  # end
  
  namespace :facebook do
    get '/voucher', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    get '/voucher/index', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    post '/voucher/registration', to: 'vouchers#registration'
    post '/voucher/sendsms', to: 'vouchers#send_sms'
    get '/startpage', to: 'vouchers#startpage'
    get '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    post '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    get '/menu', to: 'menu_tabs#index'
    post '/menu', to: 'menu_tabs#index'
  end

  root 'static_pages#index'
  get 'service-intro' => 'static_pages#service_intro'
  get 'app-intro' => 'static_pages#app_intro'
  get 'index' => 'static_pages#index'
  get 'voucher' => 'static_pages#voucher'
end

app/views/shared/_main_logo.html.haml

= link_to root_path do
  = image_tag(url)

app/views/shared/_menu_form.html.haml
= nested_form_for [:cms, menu] do |f|
  .field
    = f.label :name, t('cms.menus.name_attribute')
    = f.text_field :name, class: 'form-control', disabled: preview
  .field
    = f.label :category, t('cms.menus.category')
    = f.select :menu_category_id, MenuCategory.order('name').collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: 'form-control', disabled: preview }
  .field
    = f.label :price, t('cms.menus.price')
    = f.number_field :price, class: 'form-control', disabled: preview
  .field
    = f.fields_for :menu_components do |component_form|
      = component_form.text_field :content, disabled: preview
      = component_form.link_to_remove "Remove this component" unless preview
  .field
    = f.link_to_add "Add a component", :menu_components unless preview
  .field
    = f.label :image
    = f.file_field :image, class: 'form-control', disabled: preview
    .image-preview{ id: "image-preview-" }
      = image_tag menu.image.url
  - if restaurant
    .field
      = f.hidden_field :owner_id, value: restaurant.id
      = f.hidden_field :owner_type, value: restaurant.class
  - if preview
    = link_to t('cms.actions.go_to_edit'), edit_owner_menu_path(menu.id), class: "btn btn-info"
  - else
    = f.submit "Submit", class: "btn btn-info"

app/views/shared/_restaurant_comments_images.html.haml
.field
  = f.label :profile_image
  = f.file_field :profile_image, class: 'form-control', disabled: preview
  .image-preview{ id: "image-preview-#{f.options[:child_index]}" }
    = image_tag restaurant.profile_image_url

= f.label :iamges, "Image count #{restaurant.images_count}"
.field#restaurant-images
  - restaurant.all_images.each do |image|
    = image_tag(image[:origin])
= f.label :comments, "Foody Comment count #{restaurant.foody_comments.count} (Nguon Foody.vn)"
= f.label :comments, "Aclub Comment count #{restaurant.comments.count} (Nguon Aclub.vn)"
.field#restaurant-comments
  %ul
    - restaurant.all_comments.each do |comment|
      %li
        %label= comment.try(:content)
        %label= "Rating: #{comment.try(:rate)}"

app/views/shared/_restaurants_list.html.haml
.row.index-table-row
  .col-md-1
    = t('cms.restaurants.id')
  .col-md-3
    = t('cms.restaurants.name_attribute')
  .col-md-1
    = t('cms.restaurants.city')
  .col-md-1
    = t('cms.restaurants.category')
  .col-md-1
    = t('cms.restaurants.number_of_coupon')
  .col-md-1
    = t('cms.restaurants.total_comments')
  .col-md-1
    = t('cms.restaurants.total_photos')
  .col-md-3
    = t('cms.actions.label')
- @restaurants.each_with_index do |restaurant, index|
  .row{ class: "index-table-row #{ index%2 == 1 ? 'with-background' : '' }"}
    .col-md-1
      = restaurant.id
    .col-md-3
      = restaurant.name
    .col-md-1
      = restaurant.city.try(:name)
    .col-md-1
      = restaurant.restaurant_category.try(:name)
    .col-md-1
      = restaurant.count_available_coupons
    .col-md-1
      = restaurant.comments_count
    .col-md-1
      = restaurant.images_count
    .col-md-3
    - if current_admin.admin?
      = link_to t('cms.actions.show'), cms_restaurant_path(restaurant), class: 'btn btn-success'
      = link_to t('cms.actions.edit'), edit_cms_restaurant_path(restaurant), class: 'btn btn-primary'
      = link_to t('cms.actions.destroy'), cms_restaurant_path(restaurant), class: 'btn btn-danger', method: :delete
    - else
      = link_to t('cms.actions.show'), owner_restaurant_path(restaurant), class: 'btn btn-success'
      = link_to t('cms.actions.edit'), edit_owner_restaurant_path(restaurant), class: 'btn btn-primary'
      = link_to t('cms.actions.destroy'), owner_restaurant_path(restaurant), class: 'btn btn-danger', method: :delete
= paginate @restaurants

app/views/shared/_static_page_top_banner.html.haml
.main-menu
  %ul
    %li
      = link_to "Khuyến mãi hot", voucher_path
    %li
      %a{:href => "#"} Địa điểm
    %li
      %a{:href => "#"} Tin tức
    %li
      = link_to "Ứng dụng", app_intro_path
    %li
      %a{:href => "#"} Aclub page
    %li
      = link_to "Chúng tôi", service_intro_path
    %li
      %a{:href => "#"} Liên hệ