config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'android/index'
    get 'android/show'
    get 'android/used_coupons'
    get 'android/invitees'
    get 'android/friends'
  end

  devise_for :admins, controllers: { sessions: 'sessions', registrations: 'registrations'}
  namespace :api do
    scope '/v1' do
      resource :sessions, only: [:create] do
        post :request_phone_verification_token
      end

      resource :third_party_accounts, only: :create

      resource :registrations, only: [:create]

      resources :coupons, only: [:index, :show] do
        resources :comments, only: [:index, :create]
        collection do
          get :hot_and_nearby
          get :most_nearby
          get :best_price
          get :best_service
        end

        resources :users, only: [] do
          member do
            get :invitees
          end
        end
      end

      resources :follows, only: [:create] do
        collection do
          delete :destroy
        end
      end

      resources :users, only: [:show, :update] do
        member do
          get :available_coupons
          get :used_coupons
          get :friends
          post :email_registration
          post :email_verification
          post :resend_email_verification
        end
      end

      resources :user_coupons , only: [:create, :update, :show] do
        member do
          get :get_user_coupon
        end
      end
      

      resources :coupon_invitations, only: [:create, :update]

      resource :interactivity_statuses, only: [:index] do
        post :index
      end

      resources :venues, only: [:index, :show] do
        collection do
          get :popular_restaurants
        end
      end

      resources :restaurants, only: [:index, :show] do
        resources :comments, only: [:index, :create]
      end

      resources :envs, only: [:index]

      resources :restaurant_categories do
        member do
          get :restaurants
        end
      end
    end
  end

  namespace :cms do
    resources :coupons
    resources :venues do
      get :photos
      get :reviews
    end
    resources :restaurants
    resources :users
    resources :advertising_events
    resources :partners
    resources :restaurant_categories
    resources :admins, controller: :restaurant_owners, path: :restaurant_owners
    resources :menus
  end
  
  namespace :owner do
    resources :facebook_fanpages
    resources :coupons do
      collection do
        get :code_form
        post :redeem_code
      end
    end
    resources :restaurants

    resources :third_party_accounts, only: [:index] do
      collection do
        get 'page_list'
        post 'sync_data_from_facebook_account'
      end
    end

    resources :advertising_events
    resources :restaurants do
      collection do
        get :connect_a_restaurant
        post :restaurant_reviews
      end
    end
    resources :menus
  end

  get '/auth/facebook'
  get 'auth/:provider/callback' => 'omniauth#omniauth_callback'
  get 'auth/failure' => 'omniauth#omniauth_fallback'
  
  # resources :advertising_events, only: [:show] do
  #   collection do
  #     post '/register_phone' => 'advertising_events#register_phone'
  #     post '/verify_phone' => 'advertising_events#verify_phone'
  #     post '/resend_phone_token' => 'advertising_events#resend_phone_token'
  #     get '/reward' => 'advertising_events#reward'
  #     get '/phone_registration_page' => 'advertising_events#phone_registration_page'
  #     get '/thank_you' => 'advertising_events#thank_you'
  #   end
  # end
  
  namespace :facebook do
    get '/voucher', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    get '/voucher/index', to: 'vouchers#index'
    post '/voucher', to: 'vouchers#index'
    post '/voucher/registration', to: 'vouchers#registration'
    post '/voucher/sendsms', to: 'vouchers#send_sms'
    get '/startpage', to: 'vouchers#startpage'
    get '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    post '/voucher/restaurant-ad-event', to: 'vouchers#restaurant_advertising_event'
    get '/menu', to: 'menu_tabs#index'
    post '/menu', to: 'menu_tabs#index'
  end

  root 'static_pages#index'
  get 'service-intro' => 'static_pages#service_intro'
  get 'app-intro' => 'static_pages#app_intro'
  get 'index' => 'static_pages#index'
  get 'voucher' => 'static_pages#voucher'
end

app/controllers/api/venues_controller.rb
module Api
  class VenuesController < BaseController
    before_action :require_venue!, only: [:show]

    #Accepted params
    # required query: 'venue_name',
    # optional :latitude, :longitude, :radius (in metter)
    def index
      venues = Venue.search_and_update(venue_search_params)
      render json: ArrayPresenter.new(venues, VenuePresenter)
    end

    def show
      impressionist(@venue, Venue::VIEW)
      render json: VenueDetailsService.new(@venue).get_details
    end

    #Accepted params
    # optional :latitude, :longitude, :radius (in metter)
    def popular_restaurants
      venues = Venue.popular_restaurants(venue_search_params)
      render json: ArrayPresenter.new(venues, VenuePresenter)
    end

    private
    def venue_search_params
      params.permit(:query, :latitude, :longitude, :radius, :page)
    end

    def require_venue!
      if has_params?([:id])
        @venue = Venue.find_by(id: params[:id])
        render_errors(I18n.t('base.api.not_found'), :not_found) unless @venue
      end
    end
  end
end

app/controllers/cms/advertising_events_controller.rb
module Cms
  class AdvertisingEventsController < BaseController
    def index
      @advertising_events = AdvertisingEvent.order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('cms.advertising_events.title')
      @advertising_event = AdvertisingEvent.new
    end

    def create
      if advertising_event = AdvertisingEvent.create(advertising_event_params)
        redirect_to cms_advertising_event_path(advertising_event)
      end
    end

    def show
      @advertising_event = AdvertisingEvent.friendly.find(params[:id])
      @users = @advertising_event.users
    end

    def destroy
      if advertising_event = AdvertisingEvent.find_by_id(params[:id])
        advertising_event.destroy
        redirect_to cms_advertising_events_path
      end
    end

    def edit
      @advertising_event = AdvertisingEvent.find_by_id(params[:id])
    end

    def update
      if advertising_event = AdvertisingEvent.friendly.find(params[:id])
        advertising_event.update_attributes(advertising_event_params)
        redirect_to cms_advertising_event_path(advertising_event.id)
      end
    end

    private
    def advertising_event_params
      params.require(:advertising_event).permit(
        :description, :url, :name,
        :home_page_background, :win_page_background, :winning_rate,
        :maximum_number_of_winners, :end_at, :begin_at, :enabled,
        :reference_link_1, :reference_link_2, :user_id
      )
    end
  end
end

app/controllers/cms/base_controller.rb
module Cms
  class BaseController < ApplicationController
    before_action :authenticate_super_admin!, :set_header, :set_side_bar

    def authenticate_super_admin!
      unless current_admin.try(:admin?)
        redirect_to root_path, alert: "Acess Denied!"
      end
    end
  end
end

app/controllers/cms/coupons_controller.rb
module Cms
  class CouponsController < BaseController
    def index
      @coupons = Coupon.order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('cms.coupons.title')
      @coupon = Coupon.new
    end

    def create
      if coupon = Coupon.create(coupon_params)
        redirect_to cms_coupon_path(coupon)
      end
    end

    def show
      @coupon = Coupon.find_by_id(params[:id])
    end

    def destroy
      if coupon = Coupon.find_by_id(params[:id])
        coupon.destroy
        redirect_to cms_coupons_path
      end
    end

    def edit
      @coupon = Coupon.find_by_id(params[:id])
    end

    def update
      if coupon = Coupon.find_by_id(params[:id])
        coupon.update_attributes(coupon_params)
        redirect_to cms_coupon_path(coupon)
      end
    end

    private
    def coupon_params
      params.require(:coupon).permit(
        :description, :venue_id, :image, :restaurant_id,
        :end_date, :start_date, :required_minimum_invitees,
        :short_description, :quantity, :priority, :number_of_free_volka,
        :cash_discount, :bill_discount, :food_discount
      )
    end
  end
end

app/controllers/cms/home_controller.rb
module Cms
  class HomeController < BaseController
    def index
    end
  end
end

app/controllers/cms/menus_controller.rb
module Cms
  class MenusController < BaseController
    def edit
      @menu = Menu.find(params[:id])
    end

    def update
      menu = Menu.find(params[:id])
      if menu.update_attributes(menu_params)
        redirect_to edit_cms_restaurant_path(menu.owner)
      end 
    end

    def new
      @restaurant = Restaurant.find_by_id(params[:restaurant_id])
      @menu = Menu.new
    end

    def create
      menu = Menu.new(menu_params)
      if menu.save
        redirect_to edit_cms_restaurant_path(menu.owner)
      end
    end

    private
    def menu_params
      params.require(:menu).permit!
    end
  end
end

app/controllers/cms/partners_controller.rb
module Cms
  class PartnersController < BaseController
    def index
      @partners = Partner.order('updated_at DESC').page(params[:page])
    end

    def new
      @page_title = t('cms.partners.title')
      @partner = Partner.new
    end

    def create
      if partner = Partner.create(partner_params)
        redirect_to cms_partner_path(partner)
      end
    end

    def show
      @partner = Partner.find_by_id(params[:id])
    end

    def edit
      @partner = Partner.find_by_id(params[:id])
    end

    def update
      if partner = Partner.find_by_id(params[:id])
        partner.update_attributes(partner_params)
        redirect_to cms_partner_path(partner)
      end
    end

    def destroy
      if partner = Partner.find_by_id(params[:id])
        partner.destroy
        redirect_to cms_partners_path
      end
    end

    private
    def partner_params
      params.require(:partner).permit(:name, :url, :image, :active, :order)
    end

  end
end

app/controllers/cms/restaurant_categories_controller.rb
module Cms
  class RestaurantCategoriesController < BaseController
    def index
      @restaurant_categories = RestaurantCategory.all
    end

    def new
      @page_title = t('cms.restaurant_categories.title')
      @restaurant_category = RestaurantCategory.new
    end

    def create
      if restaurant_category = RestaurantCategory.create(restaurant_category_params)
        redirect_to cms_restaurant_category_path(restaurant_category)
      end
    end

    def show
      @restaurant_category = RestaurantCategory.find_by_id(params[:id])
    end

    def destroy
      if restaurant_category = RestaurantCategory.find_by_id(params[:id])
        restaurant_category.destroy
        redirect_to cms_restaurant_categories_path
      end
    end

    def edit
      @restaurant_category = RestaurantCategory.find_by_id(params[:id])
    end

    def update
      if restaurant_category = RestaurantCategory.find_by_id(params[:id])
        restaurant_category.update_attributes(restaurant_category_params)
        redirect_to cms_restaurant_category_path(restaurant_category)
      end
    end

    private
    def restaurant_category_params
      params.require(:restaurant_category).permit(
        :name, :alias, :image
      )
    end
  end
end

app/controllers/cms/restaurant_owners_controller.rb
module Cms
  class RestaurantOwnersController < BaseController
    def index
      @owners = Admin.owners.search(params[:query]).order('updated_at DESC').page(params[:page])
    end

    def show
      @owner = Admin.find_by_id(params[:id])
    end

    def new
      @owner = Admin.new
    end

    def update
      owner = Admin.find_by_id(params[:id])
      if owner.update_owner(owner_params)
        if params[:restaurant_id]
          Restaurant.where(owner: owner).update_all(owner_id: nil, owner_type: nil)
          Restaurant.find_by_id(params[:restaurant_id]).update_attributes(owner: owner)
        end
        redirect_to action: :show, id: owner.id
      else
        redirect_to action: :index
      end
    end

    def edit
      @owner = Admin.find_by_id(params[:id])
    end

    def create
      owner = Admin.new(owner_params)
      if owner.save
        if params[:restaurant_id]
          Restaurant.find_by_id(params[:restaurant_id]).update_attributes(owner: owner)
        end
        RestaurantOwnerInvitationJob.perform_later(owner_params[:email], owner_params[:password])
        redirect_to action: :show, id: owner.id
      else
        redirect_to action: :index
      end
    end

    def destroy
      owner = Admin.find_by_id(params[:id])
      owner.destroy
      redirect_to action: :index
    end

    private
    def owner_params
      params.require(:admin).permit(:id, :phone, :email, :password, :name, venue_ids: [])
    end
  end
end

app/controllers/cms/restaurants_controller.rb
module Cms
  class RestaurantsController < BaseController
    def index
      if params[:city]
        @restaurants = Restaurant.where(city_id: params[:city]).order('name').get_index(page: params[:page])
        @city_id = params[:city]
      else
        @restaurants = Restaurant.order('name').page(params[:page])
      end
      @restaurants = @restaurants.index_by_name(params[:query])

      respond_to do |format|
        format.html
        format.json { render json: Restaurant.index_by_name(params[:query]).pluck(:name, :id) }
      end
    end

    def show
      @restaurant = Restaurant.find_by_id(params[:id])
    end

    def edit
      @restaurant = Restaurant.find(params[:id])
    end

    def update
      restaurant = Restaurant.find_by_id(params[:id])
      if restaurant.update_attributes(restaurant_params)
        redirect_to action: :show, id: restaurant.id
      end
    end

    def destroy
      restaurant = Restaurant.find(params[:id]).destroy
    end

    private
    def restaurant_params
      params.require(:restaurant).permit!
    end
  end
end

app/controllers/cms/users_controller.rb
module Cms
  class UsersController < BaseController
    def index
      @users = User.search(params[:query]).order('updated_at DESC').page(params[:page])
    end

    def show
      @user = User.find_by_id(params[:id])
      client = Koala::Facebook::API.new(@user.facebook_token)
      begin
        data = client.get_object('me', fields: [:age_range])
        @user.update_attributes(age_range: data["age_range"])
      rescue
      end
    end

    def destroy
      user = User.find_by_id(params[:id])
      user.destroy
      redirect_to action: :index
    end
  end
end

app/controllers/cms/venues_controller.rb
module Cms
  class VenuesController < BaseController
    def index
      @venues = Venue.index_by_name(params[:query]).order('updated_at DESC').page(params[:page])
    end

    def new
      @venue = Venue.new
    end

    def create
      if venue = Venue.create(venue_params)
        redirect_to cms_venue_path(venue)
      end
    end

    def show
      @venue = Venue.find_by_id(params[:id])
      Api::VenueDetailsService.new(@venue).get_details
    end

    def destroy
      if venue = Venue.find_by_id(params[:id])
        venue.destroy
        redirect_to cms_venues_path
      end
    end

    def edit
      @venue = Venue.find_by_id(params[:id])
    end

    def update
      if venue = Venue.find_by_id(params[:id]) 
        venue.update_attributes(venue_params)
        redirect_to cms_venue_path(venue)
      end
    end

    def photos
      @venue = Venue.find_by_id(params[:venue_id])
      if @venue
        @google_place_images = @venue.google_place_images
        @facebook_photos = @venue.facebook_photos
      end
    end

    def reviews
      @venue = Venue.find_by_id(params[:venue_id])
      if @venue
        @reviews = @venue.reviews
      end
    end
    private
    def venue_params
      params.require(:venue).permit(
        :name, :description, :latitude, :longitude,
        :full_address, :formatted_phone_number, :website,
        images_attributes: [:id, :content, :_destroy]
      )
    end
  end
end

app/views/cms/venues/_form.html.haml
= nested_form_for [:cms, venue], html: { multipart: true } do |f|
  .field
    = f.label :name, t('cms.venues.name_attribute')
    = f.text_field :name, class: 'form-control', disabled: preview
  .field
    = f.label :description, t('cms.venues.description')
    = f.text_area :description, class: 'form-control', disabled: preview
  .field
    = f.label :full_address, t('cms.venues.full_address_hint')
    = f.text_field :full_address, class: 'form-control', disabled: preview
    = f.hidden_field :latitude, step: 'any'
    = f.hidden_field :longitude, step: 'any'
  .col-md-8#map{ class: "google-map" }
  .field{ style: "height: 200px" }
  .field
    = f.label :website, t('cms.venues.website')
    = f.text_field :website, class: 'form-control', disabled: preview  
  .field
    = f.label :formatted_phone_number, t('cms.venues.phone')
    = f.text_field :formatted_phone_number, class: 'form-control', disabled: preview
  - if preview
    .field
      = f.label :opening_hours, t('cms.venues.opening_hours')
      = opening_hours_tag(venue.opening_hours)
    .field
      %div
        = f.label :total_google_photos, "Total Photos From Google Place: #{venue.google_place_images.count}"
      %div
        = f.label :total_facebook_photos, "Total Photos From Facebook: #{venue.facebook_photos.count}"
      %div
        = f.label :total_s3_images, "Total Photos Uploaded by Admin: #{venue.images.count}"
      = link_to t('cms.venues.manage_photos'), cms_venue_photos_path(venue)
    .field
      %div
        = f.label :total_reviews, "Total Reviews: #{venue.reviews.count}"
      %div
        = f.label :average_rating, average_rating(venue)
      = link_to t('cms.venues.manage_reviews'), cms_venue_reviews_path(venue)
  .field
    - if preview
      = link_to t('cms.actions.go_to_edit'), edit_cms_venue_path(venue), class: "btn btn-info"
    - else
      = f.submit "Submit", class: "btn btn-info"

app/views/cms/venues/_venues_list.html.haml
.row.index-table-row
  .col-md-1
    = t('cms.venues.id')
  .col-md-2
    = t('cms.venues.name_attribute')
  .col-md-2
    = t('cms.venues.total_reviews')
  .col-md-2
    = t('cms.venues.total_photos')
  .col-md-3
    = t('cms.actions.label')
- venues.each_with_index do |venue, index|
  .row{ class: "index-table-row #{ index%2 == 1 ? 'with-background' : '' }"}
    .col-md-1
      = venue.id
    .col-md-2
      = venue.name
    .col-md-2
      = venue.reviews.count
    .col-md-2
      = venue.images.count + venue.google_place_images.count + venue.facebook_photos.count
    .col-md-3
      = link_to t('cms.actions.show'), cms_venue_path(venue), class: 'btn btn-success'
      = link_to t('cms.actions.edit'), edit_cms_venue_path(venue), class: 'btn btn-info'
      = link_to t('cms.actions.delete'), cms_venue_path(venue), class: 'btn btn-danger', method: :delete
= paginate venues

app/views/cms/venues/edit.html.haml
%div
  %span.title= t('cms.venues.edit')
= render 'form', venue: @venue, preview: false

app/views/cms/venues/index.html.haml
%div
  %span.title= t('cms.venues.name')
  = link_to t('cms.actions.new'), new_cms_venue_path, class: 'btn new-record'
= render 'layouts/search_form', base_url: cms_venues_path
= render 'cms/venues/venues_list', venues: @venues

app/views/cms/venues/new.html.haml
%div
  %span.title= t('cms.venues.new')
= render 'form', venue: @venue, preview: false

app/views/cms/venues/photos.html.haml
#mange-photos
  %h3
    Photos form google places
  - @google_place_images.each do |image|
    = image_tag(image.url, height: 200, wdith: 200)
  %h3
    Photos form facebook
  - @facebook_photos.each do |image|
    = image_tag(image.url, height: 200, wdith: 200)
  = nested_form_for [:cms, @venue], html: { multipart: true } do |f|
    .field
      = t('cms.venues.image')
      = f.fields_for :images do |image_form|  
        = image_form.file_field :content, { class: "venue-images-attributes", "index-data" => image_form.options[:child_index] }
        = image_form.link_to_remove t('cms.venues.remove_image')
        .image-preview
          = venue_image_tag(@venue, image_form)
    = f.link_to_add t('cms.venues.add_image'), :images
    %div
      = f.submit "Submit", class: "btn btn-info"

app/views/cms/venues/reviews.html.haml
%h3
  Reviews form google places
%ul#reviews
  - @reviews.each do |review|
    %li
      %div= "Rate: #{review.rating}"
      %div= "Text: #{review.text}"

app/views/cms/venues/show.html.haml
%div
  %span.title= t('cms.venues.details')
= render 'form', venue: @venue, preview: true